"""Synthetic **raw order records** and a fitted bundle, for tests that need the serving path.

Distinct from :mod:`tests.fixtures.generate_synthetic`, which produces a finished *feature
matrix*. Training-side tests want that. Anything exercising the API, the pyfunc or parity needs
what a **client actually sends** — :data:`~src.registry.pyfunc_wrapper.RAW_INPUT_COLUMNS` — and
a real fitted artifact to put it through.

**Why this lives in ``tests/fixtures/`` rather than inside a test module.** PLAN.md §13 Phase 7
requires the parity test to take its rows from ``tests/fixtures/``, never from the 2018-05 → 08
promotion evaluation window (§18 A3): that window raises unless unlocked by the gate, and the
two tests would otherwise contradict each other. §10.3 needs the same thing for CI, which has
neither the 121 MB dataset nor a Postgres instance. One module serves both, and Phase 6's
round-trip test imports from here too, so there is a single definition of "a synthetic order".

The frame is deliberately **not** a happy path. It carries a genuine null in
``dominant_category``, cold entities the snapshots have never seen, and states that exercise the
zip-centroid fallback — because a fixture where every lookup hits turns the interesting code
paths into dead code.
"""

from __future__ import annotations

from typing import Any

import numpy as np
import pandas as pd

#: Orders generated by default. Enough for a 4-fold time split to hold positives, small enough
#: that fitting an artifact and a 10-tree model stays well under a second.
N_ORDERS = 600

#: Months the snapshots cover. Starts a month before the orders so history exists for them.
SNAPSHOT_MONTHS = ("2017-04-01", "2017-08-01")


def synthetic_orders(n: int = N_ORDERS, seed: int = 7) -> pd.DataFrame:
    """Raw order records carrying every column the pyfunc requires.

    Args:
        n: Rows to generate.
        seed: Seed for the random draws. Deterministic, so parity comparisons are exact.

    Returns:
        A frame with at least :data:`~src.registry.pyfunc_wrapper.RAW_INPUT_COLUMNS`, plus
        ``order_id`` and the entity keys the snapshot join needs.
    """
    rng = np.random.default_rng(seed)
    purchased = pd.Timestamp("2017-06-01") + pd.to_timedelta(np.arange(n) * 6, unit="h")
    states = np.array(["SP", "RJ", "MG", "BA"])[np.arange(n) % 4]
    return pd.DataFrame(
        {
            "order_id": [f"o{i:05d}" for i in range(n)],
            "order_purchase_timestamp": purchased,
            "purchase_month": purchased.to_period("M").to_timestamp(),
            "promised_days": rng.integers(5, 40, n),
            "days_to_shipping_limit": rng.gamma(4.0, 1.5, n),
            "customer_state": states,
            "seller_state": np.where(np.arange(n) % 2 == 0, "SP", "RJ"),
            "customer_zip_code_prefix": np.array(["01001", "20010", "30110", "40010"])[
                np.arange(n) % 4
            ],
            "customer_seller_distance_km": rng.uniform(5, 1800, n),
            "n_seller_states": np.ones(n, dtype=int),
            "n_items": rng.integers(1, 4, n),
            "n_distinct_products": np.ones(n, dtype=int),
            "n_distinct_sellers": np.ones(n, dtype=int),
            "total_price": rng.uniform(20, 900, n),
            "total_freight": rng.uniform(5, 90, n),
            "total_weight_g": rng.uniform(100, 9000, n),
            "max_item_weight_g": rng.uniform(100, 9000, n),
            "total_volume_cm3": rng.uniform(500, 40000, n),
            "max_item_volume_cm3": rng.uniform(500, 40000, n),
            # A real null, not a sentinel: the signature and the imputation path both need one.
            "dominant_category": np.array(["cama_mesa_banho", "beleza_saude", None])[
                np.arange(n) % 3
            ],
            "dominant_payment_type": np.array(["credit_card", "boleto"])[np.arange(n) % 2],
            "max_installments": rng.integers(1, 10, n),
            "total_payment_value": rng.uniform(25, 950, n),
            "n_payment_methods": np.ones(n, dtype=int),
            "seller_id": [f"s{i % 12:03d}" for i in range(n)],
            "route": np.where(np.arange(n) % 2 == 0, "SP->SP", "RJ->RJ"),
        }
    )


def synthetic_resolved(orders: pd.DataFrame, seed: int = 8) -> pd.DataFrame:
    """Resolved history for the snapshot builder.

    Every outcome is delivered well before the orders' purchase months, so the as-of filter
    (``delivered < M``) admits all of it and the fixture does not accidentally test the
    leakage boundary — :mod:`tests.test_features_history` owns that.
    """
    rng = np.random.default_rng(seed)
    n = len(orders)
    return pd.DataFrame(
        {
            "seller_id": orders["seller_id"],
            "seller_state": orders["seller_state"],
            "route": orders["route"],
            "customer_state": orders["customer_state"],
            "dominant_category": orders["dominant_category"],
            "order_delivered_customer_date": pd.Timestamp("2017-03-01")
            + pd.to_timedelta(rng.integers(0, 40, n), unit="D"),
            "is_late": rng.random(n) < 0.08,
            "delivery_days": rng.uniform(3, 40, n),
            "handling_days": rng.uniform(0.5, 8, n),
        }
    )


def serving_records(orders: pd.DataFrame) -> pd.DataFrame:
    """Narrow a training-shaped frame to exactly what a client sends.

    Args:
        orders: Any frame carrying at least :data:`~src.registry.pyfunc_wrapper.RAW_INPUT_COLUMNS`.

    Returns:
        Those columns only, in contract order.

    The training frame carries ``purchase_month`` because the snapshot join needs it; a request
    must **not**, because serving forces it to the bundled snapshot month and the wrapper rejects
    a supplied value (D34). Going through this helper is what keeps the two shapes from being
    confused in a test.
    """
    from src.registry.pyfunc_wrapper import RAW_INPUT_COLUMNS

    return orders.loc[:, list(RAW_INPUT_COLUMNS)].copy()


def zip_centroids() -> pd.DataFrame:
    """One geocoded prefix, so the state fallback is exercised by the other three."""
    return pd.DataFrame(
        {
            "zip_code_prefix": ["01001"],
            "lat": [-23.55],
            "lng": [-46.63],
            "state": ["SP"],
            "n_points": [4],
        }
    )


def state_centroids() -> pd.DataFrame:
    """Centroids for every state the orders use, as the fallback of last resort."""
    return pd.DataFrame(
        {
            "state": ["SP", "RJ", "MG", "BA"],
            "lat": [-23.55, -22.91, -19.92, -12.97],
            "lng": [-46.63, -43.17, -43.94, -38.50],
            "n_points": [9, 7, 6, 5],
        }
    )


def fitted_bundle(n: int = N_ORDERS, seed: int = 7) -> dict[str, Any]:
    """A fitted artifact, a small real model and a wrapped predictor.

    Args:
        n: Orders to generate.
        seed: Seed threaded through the generators and the label draw.

    Returns:
        ``{"orders", "snapshots", "artifact", "model", "predictor", "labels"}``. The artifact
        carries a calibrator and a threshold, so it is wrappable; ``predictor`` is the
        :class:`~src.registry.pyfunc_wrapper.DelayPredictor` built from it.

    LightGBM with ten trees, not a stub: a stub cannot reveal a dtype mismatch between the
    training matrix and the serving matrix, which is exactly the class of skew the parity test
    exists to catch.
    """
    from lightgbm import LGBMClassifier
    from sklearn.isotonic import IsotonicRegression

    from src.features.artifact import PreprocessingArtifact
    from src.features.history import attach_history, build_all_snapshots
    from src.registry.pyfunc_wrapper import DelayPredictor

    orders = synthetic_orders(n, seed)
    resolved = synthetic_resolved(orders, seed + 1)
    months = list(pd.date_range(*SNAPSHOT_MONTHS, freq="MS"))
    snapshots = build_all_snapshots(resolved, months)

    artifact = PreprocessingArtifact.fit(
        attach_history(orders, snapshots),
        snapshots=snapshots,
        zip_centroids=zip_centroids(),
        state_centroids=state_centroids(),
        train_cutoff=orders["order_purchase_timestamp"].max(),
        # The fixture's own contract, mirroring a version's aggregates_through (D33): the
        # bundled snapshot is chosen, never inherited from "whatever was newest".
        aggregates_through=pd.Timestamp(SNAPSHOT_MONTHS[-1]) - pd.Timedelta(days=1),
    )

    features = artifact.transform_with_snapshots(orders, snapshots)

    # Labels must carry real signal, or the model returns a near-constant score and the isotonic
    # calibrator flattens it to 0.0 for every row. Parity would then pass on two paths that
    # disagree — comparing constants proves nothing. The parity test asserts the spread is real
    # so this can never silently regress.
    rng = np.random.default_rng(seed + 2)
    logit = (
        -2.0
        + 0.08 * (features["promised_days"] - features["promised_days"].mean())
        + 0.30 * (features["freight_ratio"] - features["freight_ratio"].mean())
    )
    labels = (rng.random(len(orders)) < 1.0 / (1.0 + np.exp(-logit))).astype(int)
    model = LGBMClassifier(
        n_estimators=60, num_leaves=15, min_child_samples=5, verbosity=-1, random_state=seed
    )

    # Fit on the earlier rows, calibrate on the later ones — the same disjointness Phase 5
    # enforces (§18 A2). Calibrating in-sample instead collapses the isotonic curve into a
    # two-step function, because in-sample scores separate almost perfectly. Parity then
    # compares near-constants and stops being able to fail.
    split = int(len(features) * 0.7)
    model.fit(features.iloc[:split], labels[:split])
    held_out = model.predict_proba(features.iloc[split:])[:, 1]
    calibrator = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds="clip").fit(
        held_out, labels[split:]
    )
    decided = artifact.with_decision(calibrator=calibrator, threshold=0.3)
    return {
        "orders": orders,
        "snapshots": snapshots,
        "artifact": decided,
        "model": model,
        "model_name": "lightgbm",
        "labels": labels,
        "predictor": DelayPredictor(decided, model, "lightgbm"),
    }


if __name__ == "__main__":
    bundle = fitted_bundle()
    print(f"{len(bundle['orders'])} synthetic orders")
    print("bundled snapshot:", bundle["artifact"].latest_snapshot_month.date())
    print(bundle["predictor"].predict(model_input=bundle["orders"].head(3)).to_string(index=False))
